/**
 * PDF Template Component - Professional Layout
 * Hidden from DOM until needed for PDF export
 */
const PDFTemplate = ({ 
  userInfo = {}, 
  baziData = {}, 
  insights = '',
  language = 'en'
}) => {
  const getTitle = () => {
    if (language === 'zh-CN') return '八字命盤分析報告';
    if (language === 'zh-TW') return '八字命盤分析報告';
    return 'BAZI Destiny Analysis Report';
  };

  return (
    <div 
      id="pdf-content" 
      style={{
        position: 'fixed',
        left: '-9999px',
        top: '-9999px',
        width: '210mm',
        minHeight: '297mm',
        backgroundColor: '#ffffff',
        color: '#333333',
        fontSize: '11pt',
        lineHeight: '1.6',
        fontFamily: "Arial, sans-serif",
        padding: '20mm',
        zIndex: '-9999',
        visibility: 'hidden',
        pointerEvents: 'none',
        boxSizing: 'border-box'
      }}
    >
      {/* Header */}
      <div style={styles.header}>
        <h1 style={styles.title}>{getTitle()}</h1>
        <p style={styles.subtitle}>Professional BAZI Chart Analysis</p>
      </div>

      {/* User Info */}
      <div style={styles.section}>
        <h2 style={styles.sectionTitle}>📋 Personal Information</h2>
        <table style={styles.table}>
          <tbody>
            <tr>
              <td style={styles.tableLabel}>Name:</td>
              <td style={styles.tableValue}>{userInfo.name || 'N/A'}</td>
            </tr>
            <tr>
              <td style={styles.tableLabel}>Birth Date:</td>
              <td style={styles.tableValue}>{userInfo.birthDate || 'N/A'}</td>
            </tr>
            <tr>
              <td style={styles.tableLabel}>Birth Time:</td>
              <td style={styles.tableValue}>{userInfo.birthTime || 'N/A'}</td>
            </tr>
            <tr>
              <td style={styles.tableLabel}>Gender:</td>
              <td style={styles.tableValue}>{userInfo.gender || 'N/A'}</td>
            </tr>
          </tbody>
        </table>
      </div>

      {/* Four Pillars */}
      <div style={styles.section}>
        <h2 style={styles.sectionTitle}>Four Pillars (四柱八字)</h2>
        <table style={styles.table}>
          <tbody>
            {baziData.four_pillars && Object.entries(baziData.four_pillars).map(([key, pillar]) => (
              <tr key={key}>
                <td style={styles.tableLabel}>
                  {key === 'year' ? 'Year' : key === 'month' ? 'Month' : key === 'day' ? 'Day' : 'Hour'}:
                </td>
                <td style={styles.tableValue}>
                  {pillar.stem?.name_cn || ''}{pillar.branch?.name_cn || ''} ({pillar.stem?.element || ''})
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Day Master */}
      <div style={styles.section}>
        <h2 style={styles.sectionTitle}>Day Master (日主)</h2>
        <div style={styles.dayMasterCard}>
          <p style={styles.dayMasterName}>
            {baziData.day_master?.stem_cn || 'N/A'}
          </p>
          <p style={styles.dayMasterElement}>
            {baziData.day_master?.element || 'N/A'} ({baziData.day_master?.yin_yang || 'N/A'})
          </p>
        </div>
      </div>

      {/* Elements */}
      <div style={styles.section}>
        <h2 style={styles.sectionTitle}>Five Elements Analysis (五行分析)</h2>
        <table style={styles.elementsTable}>
          <tbody>
            <tr>
              {baziData.elements && Object.entries(baziData.elements.counts || {}).map(([elem, count]) => (
                <td key={elem} style={styles.elementCell}>
                  <div style={styles.elementCount}>{count}</div>
                  <div style={styles.elementName}>{elem}</div>
                </td>
              ))}
            </tr>
          </tbody>
        </table>
        <p style={styles.balanceText}>
          <strong>Balance Status:</strong> {baziData.elements?.analysis?.balance || 'Unknown'}
        </p>
      </div>

      {/* Insights */}
      <div style={styles.section}>
        <h2 style={styles.sectionTitle}>Detailed Analysis</h2>
        <div style={styles.insightsContent}>
          {renderInsights(insights)}
        </div>
      </div>

      {/* Footer */}
      <div style={styles.footer}>
        <p style={styles.footerText}>
          Generated on: {new Date().toLocaleString()}
        </p>
        <p style={styles.footerDisclaimer}>
          This report is generated by an AI-powered BAZI analysis system for reference only.
        </p>
      </div>
    </div>
  );
};

const styles = {
  header: {
    textAlign: 'center',
    marginBottom: '20px',
    paddingBottom: '15px',
    borderBottom: '3px solid #c9a961'
  },
  
  title: {
    fontSize: '24pt',
    fontWeight: 'bold',
    color: '#c9a961',
    margin: '0 0 5px 0'
  },
  
  subtitle: {
    fontSize: '10pt',
    color: '#666666',
    margin: '0',
    fontStyle: 'italic'
  },
  
  section: {
    marginBottom: '15px',
    pageBreakInside: 'avoid'
  },
  
  sectionTitle: {
    fontSize: '13pt',
    fontWeight: 'bold',
    color: '#c9a961',
    margin: '15px 0 10px 0',
    paddingBottom: '5px',
    borderBottom: '2px solid #c9a961'
  },
  
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    marginBottom: '10px'
  },
  
  tableLabel: {
    fontWeight: 'bold',
    width: '25%',
    padding: '8px',
    backgroundColor: '#f5f5f5',
    color: '#1a1a1a',
    fontSize: '10pt',
    borderBottom: '1px solid #e0e0e0'
  },
  
  tableValue: {
    padding: '8px',
    color: '#333333',
    fontSize: '10pt',
    borderBottom: '1px solid #e0e0e0'
  },
  
  dayMasterCard: {
    padding: '15px',
    backgroundColor: '#f9f9f9',
    borderLeft: '4px solid #c9a961',
    borderRadius: '4px'
  },
  
  dayMasterName: {
    fontSize: '18pt',
    fontWeight: 'bold',
    color: '#c9a961',
    margin: '0 0 5px 0'
  },
  
  dayMasterElement: {
    fontSize: '10pt',
    color: '#666666',
    margin: '0'
  },
  
  elementsTable: {
    width: '100%',
    borderCollapse: 'collapse',
    marginBottom: '10px'
  },
  
  elementCell: {
    width: '20%',
    padding: '10px',
    textAlign: 'center',
    borderRadius: '4px',
    backgroundColor: '#f0f0f0',
    fontSize: '10pt'
  },
  
  elementCount: {
    fontSize: '16pt',
    fontWeight: 'bold',
    color: '#c9a961',
    marginBottom: '5px'
  },
  
  elementName: {
    fontSize: '9pt',
    fontWeight: 'bold',
    color: '#333333'
  },
  
  balanceText: {
    fontSize: '10pt',
    color: '#666666',
    padding: '10px',
    backgroundColor: '#fafafa',
    borderRadius: '4px',
    margin: '0'
  },
  
  insightsContent: {
    fontSize: '10pt',
    lineHeight: '1.8',
    color: '#444444'
  },
  
  footer: {
    marginTop: '30px',
    paddingTop: '15px',
    borderTop: '2px solid #c9a961',
    textAlign: 'center',
    fontSize: '9pt',
    color: '#999999'
  },
  
  footerText: {
    margin: '0 0 5px 0',
    color: '#666666'
  },
  
  footerDisclaimer: {
    margin: '0',
    fontStyle: 'italic',
    color: '#999999'
  }
};

function renderInsights(insights) {
  if (!insights) return null;

  const lines = insights.split('\n');
  const sections = [];
  let currentSection = null;
  let currentContent = [];

  lines.forEach((line) => {
    const trimmed = line.trim();
    
    if (/###\s+\d+\.?\s+/.test(trimmed)) {
      if (currentContent.length > 0 && currentSection) {
        sections.push({
          title: currentSection,
          content: currentContent.join('\n')
        });
      }
      const match = trimmed.match(/###\s+\d+\.?\s+([^\n]+)/);
      currentSection = match ? match[1] : '';
      currentContent = [];
    } else if (trimmed && !trimmed.startsWith('###')) {
      currentContent.push(trimmed);
    }
  });

  if (currentContent.length > 0 && currentSection) {
    sections.push({
      title: currentSection,
      content: currentContent.join('\n')
    });
  }

  return (
    <div>
      {sections.map((section, idx) => (
        <div key={idx} style={{ marginBottom: '12px' }}>
          <h3 style={{
            fontSize: '11pt',
            fontWeight: 'bold',
            color: '#333333',
            margin: '10px 0 5px 0',
            paddingBottom: '3px',
            borderBottom: '1px solid #ddd'
          }}>
            {section.title}
          </h3>
          <p style={{
            fontSize: '10pt',
            lineHeight: '1.6',
            color: '#444444',
            margin: '5px 0 0 0',
            whiteSpace: 'pre-wrap'
          }}>
            {section.content}
          </p>
        </div>
      ))}
    </div>
  );
}

export default PDFTemplate;