import React, { useState, useEffect, useRef, useCallback } from 'react';
import './EnhancedInsightDisplay.css';

const BOOKMARKS_KEY = 'bazi-bookmarks';

const getBookmarks = () => {
  try {
    const raw = localStorage.getItem(BOOKMARKS_KEY);
    const arr = raw ? JSON.parse(raw) : [];
    return Array.isArray(arr) ? arr : [];
  } catch {
    return [];
  }
};

const saveBookmarks = (ids) => {
  try {
    localStorage.setItem(BOOKMARKS_KEY, JSON.stringify(ids));
  } catch (e) {
    console.error('Failed to save bookmarks', e);
  }
};

const LABELS = {
  header: { en: 'BAZI Destiny Analysis', 'zh-TW': '八字命運分析', 'zh-CN': '八字命运分析', ko: '사주 운명 분석' },
  subtitle: { en: 'Structured interpretation of your life chart', 'zh-TW': '您的人生命盤結構化解讀', 'zh-CN': '您的人生命盘结构化解读', ko: '인생 차트의 구조화된 해석' },
  empty: { en: 'Insights will appear here...', 'zh-TW': '分析結果將在此顯示...', 'zh-CN': '分析结果将在此显示...', ko: '분석 결과가 여기에 표시됩니다...' },
  overview: { en: 'Overview', 'zh-TW': '總覽', 'zh-CN': '总览', ko: '개요' },
  analysis: { en: 'Analysis', 'zh-TW': '分析', 'zh-CN': '分析', ko: '분석' },
  copied: { en: 'Copied!', 'zh-TW': '已複製！', 'zh-CN': '已复制！', ko: '복사됨!' },
};

export const EnhancedInsightDisplay = ({ insights, language = 'en' }) => {
  const [sections, setSections] = useState([]);
  const [activeSection, setActiveSection] = useState(0);
  const [copiedIndex, setCopiedIndex] = useState(null);
  const [bookmarks, setBookmarksState] = useState(getBookmarks);
  const [showBookmarksOnly, setShowBookmarksOnly] = useState(false);
  const containerRef = useRef(null);
  const sectionRefs = useRef([]);

  useEffect(() => {
    let text = typeof insights === 'string' ? insights : '';
    if (!text || typeof text !== 'string') {
      setSections([]);
      return;
    }

    // Strip common AI disclaimer phrases (anywhere in text, not just at end)
    const disclaimerPatterns = [
      /以上内容由DeepSeek生成，仅供参考[。\s]*/g,
      /以上內容由DeepSeek生成，僅供參考[。\s]*/g,
      /The above content was generated by DeepSeek, for reference only\.?[\s]*/gi,
      /이상 내용은 DeepSeek이 생성했습니다[.。\s]*/g,
    ];
    for (const pattern of disclaimerPatterns) {
      text = text.replace(pattern, '')
    }
    text = text.trimEnd()

    try {
      const parsedSections = [];
      
      // First, extract the intro (everything before first ###)
      const introMatch = text.match(/^([\s\S]*?)(###\s+\d+\.)/);
      const intro = introMatch ? introMatch[1] : '';
      
      if (intro && intro.trim().length > 0) {
        parsedSections.push({
          type: 'intro',
          content: intro.trim(),
          title: 'Overview'
        });
      }

      // Now split by ### markers
      const parts = text.split(/###\s+/);
      
      // Skip first part (it's the intro we already processed)
      for (let i = 1; i < parts.length; i++) {
        const section = parts[i];
        if (!section || !section.trim || section.trim().length === 0) continue;
        const lines = section.split('\n');
        if (!lines || lines.length === 0) continue;  // ← Safe checks

        // First line should have number and title like "1. Chart Structure & Strength Analysis"
        const firstLine = lines[0] ? lines[0].trim() : '';
        
        // Extract just the title part (remove the number)
        const titleMatch = firstLine.match(/^\d+\.\s+(.+)$/);
        const title = titleMatch ? titleMatch[1] : firstLine;
        
        // Rest is content
        const content = lines.slice(1).join('\n').trim();

        if (title && content) {
          parsedSections.push({
            type: 'section',
            title: title,
            content: content
          });
        }
      }

      setSections(parsedSections);
    } catch (error) {
      console.error('Error parsing insights:', error);
      setSections([
        {
          type: 'raw',
          content: text,
          title: 'Analysis'
        }
      ]);
    }
  }, [insights]);

  // IntersectionObserver for scroll highlighting
  useEffect(() => {
    if (sections.length === 0) return;
    const observers = [];
    sectionRefs.current = sectionRefs.current.slice(0, sections.length);
    sections.forEach((_, index) => {
      const el = document.getElementById(`section-${index}`);
      if (!el) return;
      const observer = new IntersectionObserver(
        (entries) => {
          entries.forEach((entry) => {
            if (entry.isIntersecting) {
              setActiveSection(index);
            }
          });
        },
        { rootMargin: '-20% 0px -60% 0px', threshold: 0 }
      );
      observer.observe(el);
      observers.push(observer);
    });
    return () => observers.forEach((o) => o.disconnect());
  }, [sections]);

  const handleCopy = useCallback(async (index) => {
    const section = sections[index];
    if (!section?.content) return;
    try {
      await navigator.clipboard.writeText(`${section.title}\n\n${section.content}`);
      setCopiedIndex(index);
      setTimeout(() => setCopiedIndex(null), 2000);
    } catch (e) {
      console.error('Copy failed', e);
    }
  }, [sections]);

  const toggleBookmark = useCallback((index) => {
    const id = `section-${index}`;
    const next = bookmarks.includes(id) ? bookmarks.filter((b) => b !== id) : [...bookmarks, id];
    setBookmarksState(next);
    saveBookmarks(next);
  }, [bookmarks]);

  const getSectionIcon = (title) => {
    const iconMap = {
      'Chart Structure': '📊',
      'Career & Finance': '💼',
      'Relationships': '💑',
      'Health': '🏥',
      'Personality': '✨',
      'Luck Cycles': '🔄',
      'Life Guidance': '🎯',
      'Yearly Forecast': '📅',
      '流年展望': '📅',
      '命盘结构与强弱分析': '📊',
      '命盤結構與強弱分析': '📊',
      '职业与财富': '💼',
      '職業與財富': '💼',
      '关系与婚姻': '💑',
      '關係與婚姻': '💑',
      '健康与养生': '🏥',
      '健康與養生': '🏥',
      '性格与品质': '✨',
      '性格與品質': '✨',
      '幸运周期与时机': '🔄',
      '幸運周期與時機': '🔄',
      '人生指引与个人发展': '🎯',
      '人生指引與個人發展': '🎯',
      '사주 구조와 강약 분석': '📊',
      '직업과 재물': '💼',
      '관계와 결혼': '💑',
      '건강과 양생': '🏥',
      '성격과 품성': '✨',
      '대운 주기와 시기': '🔄',
      '인생 가이드와 자기계발': '🎯',
      '연간 전망': '📅',
    };
    for (const [key, icon] of Object.entries(iconMap)) {
      if (title.includes(key)) return icon;
    }
    return '📌';
  };

  const getSectionColor = (index) => {
    const colors = [
      'section-blue',
      'section-green',
      'section-purple',
      'section-orange',
      'section-pink',
      'section-teal',
      'section-amber'
    ];
    return colors[index % colors.length];
  };

  const getLabel = (key) => LABELS[key]?.[language] || LABELS[key]?.en || key;

  if (sections.length === 0) {
    const isStreaming = insights && typeof insights === 'string' && insights.length > 0;
    return (
      <div className="enhanced-insights-container">
        {isStreaming ? (
          <div className="sections-wrapper space-y-4">
            {[1, 2, 3, 4].map((i) => (
              <div key={i} className="insight-section animate-pulse bg-neutral-800/50 rounded-xl h-24 border border-white/5" />
            ))}
          </div>
        ) : (
          <div className="insights-empty">
            <p>{getLabel('empty')}</p>
          </div>
        )}
      </div>
    );
  }

  const scrollToSection = (index) => {
    const el = document.getElementById(`section-${index}`);
    el?.scrollIntoView({ behavior: 'smooth', block: 'start' });
  };

  return (
    <div className="enhanced-insights-container" ref={containerRef}>
      <div className="insights-header">
        <h2>{getLabel('header')}</h2>
        <p className="insights-subtitle">{getLabel('subtitle')}</p>
      </div>

      {/* Section navigation */}
      {sections.length > 1 && (
        <nav className="insights-nav mb-4 overflow-x-auto pb-2" aria-label="Section navigation">
          <div className="flex flex-wrap gap-2 items-center">
            {bookmarks.length > 0 && (
              <button
                type="button"
                onClick={() => setShowBookmarksOnly((v) => !v)}
                className={`px-2 py-1 rounded text-xs font-medium ${showBookmarksOnly ? 'bg-bazi-gold/30 text-amber-200' : 'bg-white/5 text-neutral-400 hover:text-amber-200'}`}
              >
                ★ {bookmarks.length}
              </button>
            )}
            <div className="flex gap-2 min-w-max overflow-x-auto">
              {sections
                .map((section, index) => ({ section, index }))
                .filter(({ index }) => !showBookmarksOnly || bookmarks.includes(`section-${index}`))
                .map(({ section, index }) => (
                  <button
                    key={index}
                    type="button"
                    onClick={() => scrollToSection(index)}
                    className={`px-3 py-1.5 rounded-lg text-xs font-medium border transition-colors whitespace-nowrap ${
                      activeSection === index
                        ? 'bg-bazi-gold/30 text-amber-200 border-bazi-gold/50'
                        : 'bg-bazi-surface/80 border-white/5 text-amber-100 hover:border-amber-500/30 hover:bg-bazi-surface'
                    }`}
                  >
                    {getSectionIcon(section.title)} {section.type === 'intro' ? getLabel('overview') : section.type === 'raw' ? getLabel('analysis') : section.title}
                  </button>
                ))}
            </div>
          </div>
        </nav>
      )}

      <div className="sections-wrapper">
        {sections
          .map((section, index) => ({ section, index }))
          .filter(({ index }) => !showBookmarksOnly || bookmarks.includes(`section-${index}`))
          .map(({ section, index }) => (
          <div
            key={index}
            id={`section-${index}`}
            ref={(el) => { sectionRefs.current[index] = el }}
            className={`insight-section ${getSectionColor(index)} ${
              section.type === 'intro' ? 'intro-section' : ''
            } ${section.type === 'raw' ? 'raw-section' : ''}`}
          >
            <div className="section-header flex items-center justify-between gap-2">
              <div className="flex items-center gap-2 min-w-0">
                <span className="section-icon">{getSectionIcon(section.title)}</span>
                <h3 className="truncate">
                  {section.type === 'intro' ? getLabel('overview') : section.type === 'raw' ? getLabel('analysis') : section.title}
                </h3>
                {bookmarks.includes(`section-${index}`) && (
                  <span className="text-amber-400 text-xs shrink-0" title="Bookmarked">★</span>
                )}
              </div>
              <div className="flex gap-1 shrink-0">
                <button
                  type="button"
                  onClick={() => toggleBookmark(index)}
                  className={`p-1.5 rounded text-xs transition-colors ${bookmarks.includes(`section-${index}`) ? 'text-amber-400' : 'text-neutral-500 hover:text-amber-300'}`}
                  aria-label={bookmarks.includes(`section-${index}`) ? 'Remove bookmark' : 'Bookmark'}
                >
                  ★
                </button>
                <button
                  type="button"
                  onClick={() => handleCopy(index)}
                  className="p-1.5 rounded text-xs text-neutral-500 hover:text-amber-300 transition-colors"
                  aria-label="Copy section"
                >
                  {copiedIndex === index ? '✓' : '⎘'}
                </button>
              </div>
            </div>

            <div className="section-content">
              {section.type === 'raw' ? (
                <div className="raw-text">{section.content}</div>
              ) : (
                <FormattedContent content={section.content} />
              )}
            </div>
          </div>
        ))}
      </div>
      {copiedIndex !== null && (
        <div className="fixed bottom-4 left-1/2 -translate-x-1/2 px-4 py-2 rounded-lg bg-bazi-gold/90 text-bazi-ink text-sm font-medium animate-fade-in">
          {getLabel('copied')}
        </div>
      )}
    </div>
  );
};

// Helper to format content
const FormattedContent = ({ content }) => {
  if (!content || typeof content !== 'string') {
    return <p>No content available</p>;
  }

  const lines = content.split('\n');

  return (
    <div className="formatted-content">
      {lines.map((line, i) => {
        const trimmed = line.trim();
        if (!trimmed) return null;

        // Bold text (between **)
        if (trimmed.includes('**')) {
          return (
            <p key={i} className="content-line">
              {trimmed.split(/\*\*([^*]+)\*\*/).map((part, idx) =>
                idx % 2 === 1 ? <strong key={idx}>{part}</strong> : part
              )}
            </p>
          );
        }

        // Bullet points starting with *
        if (trimmed.startsWith('* ')) {
          return (
            <div key={i} className="bullet-point">
              • {trimmed.replace(/^\*\s*/, '')}
            </div>
          );
        }

        // Bullet points starting with -
        if (trimmed.startsWith('- ')) {
          return (
            <div key={i} className="bullet-point">
              • {trimmed.replace(/^-\s*/, '')}
            </div>
          );
        }

        // Section separator lines (---)
        if (trimmed === '---' || trimmed === '***') {
          return <div key={i} className="section-divider" />;
        }

        // Regular paragraph
        return (
          <p key={i} className="content-line">
            {trimmed}
          </p>
        );
      })}
    </div>
  );
};

export default EnhancedInsightDisplay;
