import React from 'react'
import { localizeElement } from '../utils/localize'

/**
 * ShareCard — Hidden off-screen component rendered for html2canvas capture.
 * Portrait format 1080×1920px. "Mystical Luxury" dark/gold theme.
 *
 * Content:
 *   1. Five Elements Wheel (pentagonal radar with filled polygon)
 *   2. Day Master Strength badge
 *   3. Lucky Items row (colors, directions, numbers)
 *   4. Suitable Industries
 *   5. Life Domain Emphasis bars
 *   6. Historical Figure analogy (name only)
 */

const G = '#D4AF37' // theme gold
const GD = 'rgba(212, 175, 55, 0.15)' // gold dim
const ELEMENT_STYLES = {
  Wood:  { color: '#10b981' },
  Fire:  { color: '#ef4444' },
  Earth: { color: '#d4af37' },
  Metal: { color: '#94a3b8' },
  Water: { color: '#3b82f6' },
}
const ELEMENT_ORDER = ['Wood', 'Fire', 'Earth', 'Metal', 'Water']

const DOMAIN_KEYS = ['career', 'wealth', 'relationships', 'health', 'learning']
const DOMAIN_LABELS = {
  career:        { en: 'Career',        'zh-TW': '事業',       'zh-CN': '事业',       ko: '직업' },
  wealth:        { en: 'Wealth',        'zh-TW': '財富',       'zh-CN': '财富',       ko: '재물' },
  relationships: { en: 'Relationships', 'zh-TW': '關係',       'zh-CN': '关系',       ko: '관계' },
  health:        { en: 'Health',        'zh-TW': '健康',       'zh-CN': '健康',       ko: '건강' },
  learning:      { en: 'Learning',      'zh-TW': '學習',       'zh-CN': '学习',       ko: '학습' },
}
const DOMAIN_COLORS = {
  career: '#D4AF37', wealth: '#10b981', relationships: '#ef4444', health: '#3b82f6', learning: '#a78bfa',
}

const LABELS = {
  en: {
    title: 'BAZI Analysis',
    subtitle: 'Five Elements Profile',
    dayMaster: 'Day Master',
    strong: 'Strong', weak: 'Weak', balanced: 'Balanced',
    luckyColors: 'Colors', luckyDirections: 'Directions', luckyNumbers: 'Numbers',
    industries: 'Suitable Industries',
    lifeDomains: 'Life Domains',
    journeyTitle: 'Your Life Journey Mirrors',
    journeyTitleFallback: 'Life Journey',
    footer: 'Generated by BAZI AI',
  },
  'zh-TW': {
    title: '八字命理分析',
    subtitle: '五行能量分佈',
    dayMaster: '日主',
    strong: '身強', weak: '身弱', balanced: '中和',
    luckyColors: '顏色', luckyDirections: '方位', luckyNumbers: '數字',
    industries: '適合行業',
    lifeDomains: '人生領域',
    journeyTitle: '你的人生旅程如同',
    journeyTitleFallback: '人生旅程',
    footer: '由 BAZI AI 生成',
  },
  'zh-CN': {
    title: '八字命理分析',
    subtitle: '五行能量分布',
    dayMaster: '日主',
    strong: '身强', weak: '身弱', balanced: '中和',
    luckyColors: '颜色', luckyDirections: '方位', luckyNumbers: '数字',
    industries: '适合行业',
    lifeDomains: '人生领域',
    journeyTitle: '你的人生旅程如同',
    journeyTitleFallback: '人生旅程',
    footer: '由 BAZI AI 生成',
  },
  ko: {
    title: '사주 분석',
    subtitle: '오행 에너지 분포',
    dayMaster: '일주',
    strong: '신강', weak: '신약', balanced: '중화',
    luckyColors: '색상', luckyDirections: '방향', luckyNumbers: '숫자',
    industries: '적합 업종',
    lifeDomains: '인생 영역',
    journeyTitle: '당신의 인생 여정은',
    journeyTitleFallback: '인생 여정',
    footer: 'BAZI AI 생성',
  },
}

/* ── helpers ── */
const pickLang = (obj, lang) => {
  if (!obj) return ''
  if (typeof obj === 'string') return obj
  return obj[lang] || obj.en || ''
}

/** Extract a historical figure name from the journey overview text */
const extractHistoricalFigure = (text) => {
  if (!text || typeof text !== 'string') return null
  // English
  let m = text.match(/(?:resembles?|echoes?|mirrors?|akin\s+to|like)\s+(?:that\s+of\s+)?([A-Z][a-zA-Z\s]{2,30}?)(?:\s*[—–\-,.(]|because|$)/i)
    || text.match(/(?:Historical\s+(?:Analogy|Figure))[:\s—–-]*\s*([A-Z][a-zA-Z\s]+?)(?:\s*[—–\-,.(]|$)/i)
  if (m) return m[1].trim()
  // Chinese (simplified + traditional)
  m = text.match(/(?:如同|类似|仿佛|好比|恰如|犹如|堪比|類似|彷彿|猶如)\s*[「""]?([^\s「""，。,.\n]{2,8})[」""]?/)
    || text.match(/(?:历史人物|歷史人物)[：:\s]*[「""]?([^\s「""，。,.\n]{2,8})[」""]?/)
  if (m) return m[1].trim()
  return null
}


const ShareCard = React.forwardRef(({ baziChart, sectionContent, language = 'en' }, ref) => {
  const L = LABELS[language] || LABELS.en
  const lang = language || 'en'

  // ── Element data ──
  const counts = baziChart?.elements?.counts || {}
  const total = Object.values(counts).reduce((a, b) => a + b, 0) || 1
  const percentages = ELEMENT_ORDER.map(el => ({
    element: el,
    percent: Math.round(((counts[el] || 0) / total) * 100),
  }))

  // ── Day Master ──
  const dmElement = baziChart?.day_master?.element || '?'
  const dmStrength = baziChart?.use_god?.dm_strength || baziChart?.day_master?.strength || 'balanced'

  // ── Lucky items ──
  const advice = baziChart?.use_god?.advice || {}
  const luckyColors = pickLang(advice.colors, lang)
  const luckyDirections = pickLang(advice.directions, lang)
  const luckyNumbers = typeof advice.numbers === 'object' ? pickLang(advice.numbers, lang) : (advice.numbers || '')

  // ── Suitable Industries ──
  const suitableIndustries = pickLang(advice.careers, lang)

  // ── Life Domain Emphasis ──
  const agePeriods = baziChart?.age_periods || []
  const domainTotals = { career: 0, wealth: 0, relationships: 0, health: 0, learning: 0 }
  agePeriods.forEach(p => {
    const d = p.domains || {}
    DOMAIN_KEYS.forEach(k => { domainTotals[k] += d[k] || 0 })
  })
  const maxDomain = Math.max(...Object.values(domainTotals), 1)

  // ── Historical Figure from Journey Overview ──
  const journeyOverview = sectionContent?.age_periods_timeline?.journey_overview || ''
  const journeyText = typeof journeyOverview === 'string' ? journeyOverview : ''
  const historicalFigure = extractHistoricalFigure(journeyText)

  // ── Five Elements Wheel SVG ──
  const svgSize = 540
  const center = svgSize / 2
  const radius = svgSize * 0.36
  const nodeR = 48

  const nodePoints = ELEMENT_ORDER.map((el, i) => {
    const angle = (i * 72 - 90) * (Math.PI / 180)
    return { x: center + radius * Math.cos(angle), y: center + radius * Math.sin(angle), element: el, percent: percentages[i].percent }
  })

  const radarPoints = ELEMENT_ORDER.map((_, i) => {
    const angle = (i * 72 - 90) * (Math.PI / 180)
    const pct = percentages[i].percent / 100
    const r = radius * (0.1 + pct * 0.9)
    return `${center + r * Math.cos(angle)},${center + r * Math.sin(angle)}`
  }).join(' ')

  const outerPath = nodePoints.map(p => `${p.x},${p.y}`).join(' ')
  const starPath = `M${nodePoints[0].x},${nodePoints[0].y} L${nodePoints[2].x},${nodePoints[2].y} L${nodePoints[4].x},${nodePoints[4].y} L${nodePoints[1].x},${nodePoints[1].y} L${nodePoints[3].x},${nodePoints[3].y} Z`

  const strengthLabel = dmStrength === 'strong' ? L.strong : dmStrength === 'weak' ? L.weak : L.balanced
  const strengthColor = dmStrength === 'strong' ? '#ef4444' : dmStrength === 'weak' ? '#3b82f6' : G

  /* ═══════════════════ CARD RENDER ═══════════════════ */
  return (
    <div
      ref={ref}
      style={{
        position: 'fixed', left: '-9999px', top: '-9999px', pointerEvents: 'none',
        width: '1080px', height: '1920px',
        background: 'linear-gradient(180deg, #050505 0%, #0a0a0a 30%, #120f08 60%, #0a0a0a 100%)',
        fontFamily: "'Playfair Display', 'Source Han Serif SC', 'Noto Serif SC', 'Noto Serif TC', serif",
        color: '#fff', overflow: 'hidden',
        display: 'flex', flexDirection: 'column',
      }}
    >
      {/* Corner ornaments */}
      {[[36,36,'Top','Left'],[36,null,'Top','Right'],[null,36,'Bottom','Left'],[null,null,'Bottom','Right']].map(([t,l,v,h],i) => (
        <div key={i} style={{ position:'absolute', ...(t!=null?{top:t}:{bottom:36}), ...(l!=null?{left:l}:{right:36}), width:70, height:70, [`border${v}`]:`2px solid ${G}`, [`border${h}`]:`2px solid ${G}`, opacity:0.3 }} />
      ))}

      {/* ── Content wrapper: vertically centered with even spacing ── */}
      <div style={{
        flex: 1, display: 'flex', flexDirection: 'column',
        justifyContent: 'center', alignItems: 'stretch',
        padding: '60px 0 80px',
        gap: 60,
      }}>

        {/* ── Title ── */}
        <div style={{ textAlign: 'center' }}>
          <div style={{ fontSize: 26, letterSpacing: 10, color: G, textTransform: 'uppercase', opacity: 0.5, lineHeight: 1.2 }}>
            {L.title}
          </div>
          <div style={{ fontSize: 54, fontWeight: 'bold', color: '#fff', marginTop: 8, lineHeight: 1.1 }}>
            {L.subtitle}
          </div>
          <div style={{ width: 140, height: 2, background: `linear-gradient(90deg, transparent, ${G}, transparent)`, margin: '14px auto 0' }} />
        </div>

        {/* ── Five Elements Wheel ── */}
        <div style={{ display: 'flex', justifyContent: 'center' }}>
          <svg width={svgSize} height={svgSize} viewBox={`0 0 ${svgSize} ${svgSize}`}>
            <circle cx={center} cy={center} r={radius + 35} fill="none" stroke={G} strokeWidth="1" strokeOpacity="0.08" />
            <circle cx={center} cy={center} r={radius} fill="none" stroke={G} strokeWidth="1" strokeOpacity="0.15" />
            <polygon points={outerPath} fill="none" stroke={G} strokeWidth="1.5" strokeOpacity="0.25" />
            <path d={starPath} fill="none" stroke={G} strokeWidth="0.8" strokeOpacity="0.1" />
            <defs>
              <radialGradient id="scRadar" cx="0.5" cy="0.5" r="0.5">
                <stop offset="0%" stopColor={G} stopOpacity="0.45" />
                <stop offset="100%" stopColor={G} stopOpacity="0.08" />
              </radialGradient>
            </defs>
            <polygon points={radarPoints} fill="url(#scRadar)" stroke={G} strokeWidth="2" strokeOpacity="0.75" />
            {nodePoints.map((p) => {
              const st = ELEMENT_STYLES[p.element]
              return (
                <g key={p.element}>
                  <circle cx={p.x} cy={p.y} r={nodeR} fill="#0e0e12" stroke={st.color} strokeWidth="3" />
                  <text x={p.x} y={p.y - 4} textAnchor="middle" fill="#fff" fontSize="28" fontWeight="bold" fontFamily="sans-serif">{p.percent}%</text>
                  <text x={p.x} y={p.y + 22} textAnchor="middle" fill={st.color} fontSize="20" fontWeight="600" fontFamily="serif">{localizeElement(p.element, lang)}</text>
                </g>
              )
            })}
          </svg>
        </div>

        {/* ── Day Master Badge ── */}
        <div style={{ display: 'flex', justifyContent: 'center' }}>
          <div style={{
            background: 'rgba(212, 175, 55, 0.06)', border: `1.5px solid ${G}40`,
            borderRadius: 60, padding: '16px 60px', overflow: 'hidden',
          }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 28, transform: 'translateY(-12px)' }}>
              <span style={{ fontSize: 24, color: '#a3a3a3', letterSpacing: 4, textTransform: 'uppercase', lineHeight: 1 }}>
                {L.dayMaster}
              </span>
              <span style={{ fontSize: 42, fontWeight: 'bold', color: ELEMENT_STYLES[dmElement]?.color || G, lineHeight: 1, transform: 'translateY(-6px)' }}>
                {localizeElement(dmElement, lang)}
              </span>
              <span style={{ fontSize: 24, color: strengthColor, fontWeight: '600', lineHeight: 1 }}>
                {strengthLabel}
              </span>
            </div>
          </div>
        </div>

        {/* ── Lucky Items Row ── */}
        <div style={{ display: 'flex', justifyContent: 'center', gap: 28, padding: '0 60px' }}>
          {[
            { label: L.luckyColors, value: luckyColors, icon: '◆' },
            { label: L.luckyDirections, value: luckyDirections, icon: '✦' },
            { label: L.luckyNumbers, value: luckyNumbers, icon: '✧' },
          ].map((item, i) => (
            <div key={i} style={{
              flex: 1, background: 'rgba(255,255,255,0.025)', border: `1px solid ${GD}`,
              borderRadius: 18, padding: '22px 16px', textAlign: 'center', overflow: 'hidden',
            }}>
              <div style={{ transform: 'translateY(-16px)' }}>
                <div style={{ fontSize: 36, color: G, lineHeight: 1, marginBottom: 10 }}>{item.icon}</div>
                <div style={{ fontSize: 18, color: '#a3a3a3', letterSpacing: 2, textTransform: 'uppercase', lineHeight: 1, marginBottom: 10 }}>
                  {item.label}
                </div>
                <div style={{ fontSize: 24, color: '#e5e5e5', lineHeight: 1.3, fontWeight: '500' }}>
                  {item.value || '—'}
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* ── Suitable Industries ── */}
        {suitableIndustries && (
          <div style={{ margin: '0 60px', background: 'rgba(212,175,55,0.04)', border: `1px solid ${GD}`, borderRadius: 18, padding: '22px 30px', overflow: 'hidden' }}>
            <div style={{ transform: 'translateY(-14px)' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 14, marginBottom: 10 }}>
                <span style={{ fontSize: 30, color: G, lineHeight: 1 }}>◈</span>
                <span style={{ fontSize: 22, color: G, letterSpacing: 3, textTransform: 'uppercase', fontWeight: '600', lineHeight: 1 }}>
                  {L.industries}
                </span>
              </div>
              <div style={{ fontSize: 26, color: '#d4d4d4', lineHeight: 1.5 }}>
                {suitableIndustries}
              </div>
            </div>
          </div>
        )}

        {/* ── Life Domain Emphasis ── */}
        {agePeriods.length > 0 && (
          <div style={{ margin: '0 60px' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 14, marginBottom: 16, transform: 'translateY(-10px)' }}>
              <span style={{ fontSize: 30, color: G, lineHeight: 1 }}>◇</span>
              <span style={{ fontSize: 22, color: G, letterSpacing: 3, textTransform: 'uppercase', fontWeight: '600', lineHeight: 1 }}>
                {L.lifeDomains}
              </span>
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
              {DOMAIN_KEYS.map(key => {
                const value = domainTotals[key]
                const pct = Math.max(8, Math.round((value / maxDomain) * 100))
                const label = DOMAIN_LABELS[key]?.[lang] || DOMAIN_LABELS[key]?.en || key
                const color = DOMAIN_COLORS[key] || G
                return (
                  <div key={key} style={{ display: 'flex', alignItems: 'center', gap: 18 }}>
                    <span style={{ fontSize: 22, color: '#b0b0b0', width: 160, textAlign: 'right', flexShrink: 0, lineHeight: 1, transform: 'translateY(-13px)' }}>
                      {label}
                    </span>
                    <div style={{ flex: 1, height: 22, background: 'rgba(255,255,255,0.04)', borderRadius: 11, overflow: 'hidden' }}>
                      <div style={{ width: `${pct}%`, height: '100%', background: `linear-gradient(90deg, ${color}90, ${color}40)`, borderRadius: 11 }} />
                    </div>
                    <span style={{ fontSize: 20, color, width: 60, textAlign: 'left', fontWeight: '600', lineHeight: 1, transform: 'translateY(-13px)' }}>
                      {pct}%
                    </span>
                  </div>
                )
              })}
            </div>
          </div>
        )}

        {/* ── Historical Figure / Life Journey ── */}
        {historicalFigure && (
          <div style={{
            margin: '0 60px', background: 'linear-gradient(135deg, rgba(212,175,55,0.08), rgba(212,175,55,0.02))',
            border: `1.5px solid ${G}30`, borderRadius: 20,
            padding: '28px 34px', textAlign: 'center', overflow: 'hidden',
          }}>
            <div style={{ transform: 'translateY(-17px)' }}>
              <div style={{ fontSize: 22, color: '#a3a3a3', letterSpacing: 3, textTransform: 'uppercase', lineHeight: 1, marginBottom: 14 }}>
                {L.journeyTitle}
              </div>
              <div style={{ fontSize: 48, fontWeight: 'bold', color: G, letterSpacing: 2, lineHeight: 1 }}>
                {historicalFigure}
              </div>
            </div>
          </div>
        )}

        {/* Fallback: if no historical figure found but journey text exists */}
        {!historicalFigure && journeyText && (
          <div style={{ margin: '0 60px', background: 'rgba(212,175,55,0.04)', border: `1px solid ${GD}`, borderRadius: 18, padding: '20px 30px' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 14, marginBottom: 12 }}>
              <span style={{ fontSize: 30, color: G, lineHeight: 1 }}>✦</span>
              <span style={{ fontSize: 22, color: G, letterSpacing: 3, textTransform: 'uppercase', fontWeight: '600', lineHeight: 1 }}>
                {L.journeyTitleFallback}
              </span>
            </div>
            <div style={{ fontSize: 24, color: '#d4d4d4', lineHeight: 1.5 }}>
              {journeyText.replace(/\*\*/g, '').replace(/\n+/g, ' ').trim().substring(0, 150)}...
            </div>
          </div>
        )}

      </div>

      {/* ── Footer ── */}
      <div style={{
        textAlign: 'center', fontSize: 18, color: G, opacity: 0.3, letterSpacing: 5,
        paddingBottom: 44,
      }}>
        {L.footer}
      </div>
    </div>
  )
})

ShareCard.displayName = 'ShareCard'
export default ShareCard
