/**
 * Strip common AI disclaimer phrases from text.
 * Matches anywhere in text (no $ anchor), removes all occurrences (g flag),
 * and trims optional period + whitespace ([。\s]*).
 */
const DISCLAIMER_PATTERNS = [
  /以上内容由DeepSeek生成，仅供参考[。\s]*/g,
  /以上内容由DeepSeek生成，仅供娱乐参考[。\s]*/g,
  /以上內容由DeepSeek生成，僅供參考[。\s]*/g,
  /以上內容由DeepSeek生成，僅供娛樂參考[。\s]*/g,
  /The above content was generated by DeepSeek, for reference only\.?[\s]*/gi,
  /이상 내용은 DeepSeek이 생성했습니다[.。\s]*/g,
]

export function stripDisclaimers(text) {
  if (!text || typeof text !== 'string') return text
  let result = text
  for (const pattern of DISCLAIMER_PATTERNS) {
    result = result.replace(pattern, '')
  }
  return result.trimEnd()
}
